# Generated by Django 3.1.7 on 2021-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
